### ISSUE TITLE
Provide clearer info

### ISSUE THREAD

**Issue by mazafra1** [henry-spanka/homebridge-nubli#1]
Hi henry,

Please accept a couple of suggestions from me to provide clearer info about this project:
1.- Add to README that smartlock must be in pairing mode (and hopefully how to achieve that) when launching the pair.js script.
2.- What are the expected features once we have running this plugin in homebridge? What are the main differences compared to adding the smartlock directly to Home app?
3.- Is it mandatory to remove the smartlock from Home app (if existing) before adding it through Homebridge? 

Thanks for all your great work here.

**Comment by henry-spanka** [comment]
Hi,
thank you for the suggestions. I have update the readme. Please let me know if anything is missing.

Note that the pair example is currently not working correctly.
See: henry-spanka/nubli#1
