### ISSUE TITLE
can't connect Nuki V1

### ISSUE THREAD

**Issue by testpaul999** [henry-spanka/homebridge-nubli#2]
Hi, have trouble with connecting Niku V1
sudo node /usr/lib/node_modules/nubli/examples/pair.js
2019-9-10 14:11:46 state change: poweredOn
Ready to scan :)
2019-9-10 14:11:46 Started scanning
2019-9-10 14:11:46 Peripheral matched filter: 54d27235c7e1 - Nuki_14XXXX
2019-9-10 14:11:46 Stopped scanning
2019-9-10 14:11:55 54d27235c7e1: disconnected

any hints for me please.

thanks

**Comment by henry-spanka** [comment]
Hi,
this is probably related to henry-spanka/nubli#1. I have pushed an updated version of the plugin (1.0.2) to npm. Update the plugin to the latest version and try again.

**Comment by testpaul999** [comment]
Ok, I’ll try.

Thx

Liebe Grüße

Jens-Uwe

**Comment by testpaul999** [comment]
sorry wont work
see here

386pi:/usr/lib/node_modules/nubli/examples$ node pair.js
2019-9-10 21:47:00 state change: poweredOn
Ready to scan :)
2019-9-10 21:47:00 Started scanning
2019-9-10 21:47:00 Peripheral matched filter: 54d27235c7e1 - Nuki_1435C7E1
2019-9-10 21:47:00 Stopped scanning
2019-9-10 21:47:00 54d27235c7e1: connected
connected
2019-9-10 21:47:00 54d27235c7e1: All characteristics found. Trying to pair
successfully paired
(node:3770) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './config/54d27235c7e1.json'
(node:3770) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3770) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2019-9-10 21:47:12 54d27235c7e1: disconnected

the same with sudo 
it looks like that it is not possible to create the folder "config"
see "ll"
pi@386pi:/usr/lib/node_modules/nubli$ ll
insgesamt 60
drwxr-xr-x   4 root root  4096 Sep 10 21:39 ./
drwxr-xr-x 401 root root 16384 Sep 10 21:39 ../
-rw-r--r--   1 root root    98 Okt 26  1985 CHANGELOG.md
-rw-r--r--   1 root root  3211 Okt 26  1985 CODE_OF_CONDUCT.md
drwxr-xr-x   3 root root  4096 Sep 10 21:39 dist/
drwxr-xr-x   2 root root  4096 Sep 10 21:39 examples/
-rw-r--r--   1 root root  1068 Okt 26  1985 LICENSE
-rw-r--r--   1 root root  1959 Sep 10 21:39 package.json
-rw-r--r--   1 root root  5951 Okt 26  1985 README.md
-rw-r--r--   1 root root  5570 Okt 26  1985 tsconfig.json

**Comment by testpaul999** [comment]
also the same if i'm root

**Comment by testpaul999** [comment]
ok have fix by mkdir "config" and run pair.js again.
get a file 54d27235c7e1.json (mac-adress.json)
copy this file to /var/homebridge/nubliConfig
do the config and restart homebridge.
config.json
{
            "platform": "Nubli",
            "configPath": "./var/homebridge/nubliConfig/",
            "debug": true,
            "locks": [
                {
                    "name": "Haustuer",
                    "uuid": "54d27235c7e1"
                }
            ]
        }

but the led of the nuki will blinking the whole time. so I'm thing it is not paired.

**Comment by testpaul999** [comment]
at least a new scan run in to the forest ;-)
pi@386pi:/usr/lib/node_modules/nubli/examples$ node pair.js
2019-9-10 22:15:32 state change: poweredOn
Ready to scan :)
2019-9-10 22:15:32 Started scanning
2019-9-10 22:15:32 Peripheral matched filter: 54d27235c7e1 - Nuki_1435C7E1
2019-9-10 22:15:32 Stopped scanning
2019-9-10 22:15:32 Started scanning
2019-9-10 22:15:41 54d27235c7e1: disconnected
2019-9-10 22:16:32 54d27235c7e1: No Advertisement received from Smart Lock within 60 seconds - Marking Smart Lock as stale.
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!
noble: unknown peripheral null connected!

**Comment by testpaul999** [comment]
my node version
node -v
v8.16.1

**Comment by testpaul999** [comment]
this are from homebridge journal
86pi homebridge[3934]: [2019-9-12 11:59:39] [Nubli] Discovered Smart Lock with UUID 54d27235c7e1
Sep 12 11:59:39 386pi homebridge[3934]: 2019-9-12 11:59:39 54d27235c7e1: Reading lock state
Sep 12 11:59:39 386pi homebridge[3934]: 2019-9-12 11:59:39 54d27235c7e1: Executing command
Sep 12 11:59:39 386pi homebridge[3934]: Thu, 12 Sep 2019 09:59:39 GMT hci create le conn - writing: 010d2019600030000000e1c73572d2540006000c000000c80004000600
Sep 12 11:59:39 386pi homebridge[3934]: Thu, 12 Sep 2019 09:59:39 GMT hci onSocketData: 040f040d010d20
Sep 12 11:59:39 386pi homebridge[3934]: Thu, 12 Sep 2019 09:59:39 GMT hci 	event type = 4
Sep 12 11:59:39 386pi homebridge[3934]: Thu, 12 Sep 2019 09:59:39 GMT hci 	sub event type = 15
Sep 12 11:59:39 386pi homebridge[3934]: Thu, 12 Sep 2019 09:59:39 GMT hci 		status = 13
Sep 12 11:59:39 386pi homebridge[3934]: Thu, 12 Sep 2019 09:59:39 GMT hci 		cmd = 8205
Sep 12 11:59:39 386pi homebridge[3934]: [2019-9-12 11:59:39] [Nubli] Failed to get Smart Lock configuration. An unknown error occurred

**Comment by henry-spanka** [comment]
Have you successfully paired the lock? The data the smart locks sends back (`040f040d010d20`) is not valid according to their documentation so It's hard to interpret the results. Please try to manually run the `getLockState.js` script in the Nubli directory and check if there are any errors.

**Comment by testpaul999** [comment]
Hi, have buy the bridge and this will run fine.


Liebe Grüße

Jens-Uwe

**Comment by henry-spanka** [comment]
Alright, no problem. As I don't have a Nuki Smart Lock due to security and reliability issues I can only make limited changes to this Bluetooth API. 

I'll close this issue.
